[build]
builder = "nixpacks"

[deploy]
startCommand = "daphne -v 1 -b 0.0.0.0 -p $PORT chess_backend.asgi:application"
healthcheckPath = "/health-root-v6/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[env]
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "chess_backend.settings"
ALLOWED_HOSTS = "*"
DEBUG = "true"
DISABLE_COLLECTSTATIC = "1"
VERCEL_FRONTEND_URL = "https://chess-game-app-delta.vercel.app"
