name: chess
description: A chess game with Firebase authentication
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.5.0

  # Firebase Authentication
  firebase_auth: ^5.0.0

  # Google Sign-In
  google_sign_in: ^6.1.5

  # Routing
  go_router: ^14.0.0

  #For OTP timer and countdown
  pin_code_fields: ^8.0.1
  timer_count_down: ^2.2.2

  #For OTP Verification
  firebase_messaging: ^15.0.0

  #For better UI
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
