name: chess_bishal
description: A chess game with Django authentication
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.1
  go_router: ^13.0.1
  http: ^1.2.1
  pin_code_fields: ^8.0.1
  flutter_webrtc: ^0.12.0
  web_socket_channel: ^2.4.0
  permission_handler: ^11.3.0
  flutter_inappwebview: ^6.0.0
  audioplayers: ^5.2.1
  mqtt_client: ^10.3.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.2
  flutter_background_service: ^5.0.10
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/chess_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/sounds/ringtone.mp3
    - assets/sounds/call_ringtone.mp3
